version: '3'
services:
  #监控管理台服务
  user-service:
    image: cike/user-service:0.0.1-SNAPSHOT
    container_name: sc-user-service
#    restart: always
    networks:
      - sc-net
    ports:
      - 8084:8084
    #指定monitor运行时在yml文件中的nacos的地址
    env_file: .env
    environment:
      TZ: Asia/Shanghai

#  sentinel-dashboard:
#    image: cike/sentinel-dashboard-docker:latest
#    container_name: sc-sentinel-dashboard
#    restart: always
#    networks:
#      - sc-net
#    ports:
#      - 8021:8021
#    env_file: .env
networks:
  sc-net:
    external: false