version: '3'
services:
  #监控管理台服务
  micro-oauth2-auth:
    image: cike/micro-oauth2-auth:1.0.0
    container_name: sc-micro-oauth2-auth
#    restart: always
    networks:
      - sc-net
    ports:
      - 9401:9401
    #指定monitor运行时在yml文件中的nacos的地址
    env_file: .env
    environment:
      TZ: Asia/Shanghai

#  sentinel-dashboard:
#    image: cike/sentinel-dashboard-docker:latest
#    container_name: sc-sentinel-dashboard
#    restart: always
#    networks:
#      - sc-net
#    ports:
#      - 8021:8021
#    env_file: .env
networks:
  sc-net:
    external: false