version: '3'
services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to. Scribe is disabled by default.
  zipkin:
    image: openzipkin/zipkin:2.21.1
    container_name: zipkin
    networks:
      - sc-net
    environment:
      # 指定elasticsearch为数据库
      - STORAGE_TYPE=elasticsearch
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
#    network_mode: host
    volumes:
      - ../data/zipkin/logs:/logs
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    #指定elasticsearch数据库的地址
    env_file: .env


networks:
  sc-net:
    external: false