version: '3'
services:

  logstash:
    image: logstash:7.9.0
    container_name: sc-logstash
    networks:
      - sc-net
    environment:
      - TZ=Asia/Shanghai
      - elasticsearch.hosts=http://localhost:9200

    volumes:
      - ./config/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf #挂载logstash的配置文件
#    depends_on:
#      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563


networks:
  sc-net:
    external: false