version: '3'
services:
  nacos:
    image: nacos/nacos-server:1.1.3
    container_name: sc-nacos-standalone
    networks:
      - sc-net
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - nacos.core.auth.enabled=true
    volumes:
      - ../data/nacos/logs/:/home/nacos/logs
    ports:
      - "8848:8848"

#  prometheus:
#    container_name: sc-prometheus
#    image: prom/prometheus:latest
#    networks:
#      - sc-net
#    volumes:
#      - ./nacos/prometheus.yaml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    depends_on:
#      - nacos
#    restart: on-failure

networks:
  sc-net:
    external: false