spring:
  application:
    name: mall-search
  profiles:
    active: dev #默认为开发环境

server:
  port: 8087



#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml



