spring:
  application:
    name: recommend-service
  profiles:
    active: dev #默认为开发环境

server:
  port: 8089



#mybatis:
#  mapper-locations:
#    - classpath:dao/*.xml
#    - classpath*:com/**/mapper/*.xml



